name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./functions
        run: npm install
      - name: Run Deploy
        working-directory: ./functions
        run: npm run deploy --token ${{ secrets.FIREBASE_TOKEN }}
